### ISSUE TITLE
Missing anchor points on digits in Grantha

### ISSUE THREAD

**Issue by dscorbett** [notofonts/grantha#6]
### Font
NotoSansGrantha-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansGrantha-Regular.ttf
Date: 2018-11-15

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
The digits in Noto Sans Grantha don’t have anchor points.

### Character data
௪𑍧௫𑍧
U+0BEA TAMIL DIGIT FOUR
U+11367 COMBINING GRANTHA DIGIT ONE
U+0BEB TAMIL DIGIT FIVE
U+11367 COMBINING GRANTHA DIGIT ONE

### Screenshot
![௪𑍧௫𑍧](https://user-images.githubusercontent.com/1124347/49330100-f7041580-f557-11e8-8fc3-0fa7dfa20800.png)

**Comment by SKing-2003** [comment]
Unfortunately, this issue seems to have resurfaced.
![image](https://user-images.githubusercontent.com/107930743/175048066-b66d4b43-e64e-4395-8cfa-a0f27e65af1b.png)

**Comment by simoncozens** [comment]
It turns out you are both right!

Simeon's screenshot above was taken in Crowbar which uses Harfbuzz. The problem is that Harfbuzz guesses the script based on the first character of the buffer, decides that it's Tamil, and applies `taml`/`tml2` shaping. In the current build, the mark-to-base lookups are all filed under `gran/dflt`, and so Tamil shaping won't cause the attachments to be applied. Put an obviously Grantha character before the digits, and everything works.

So this will happen in the incredibly rare case that the first character in a shaping run is a Tamil digit...

**Comment by simoncozens** [comment]
I'm so tempted to add `languagesystem tml2 dflt` just to deal with this one specific case...

**Comment by jamadagni** [comment]
This combination of combining 1 above with Tamil digits will naturally occur only in Sama Vedic texts and there will be certainly a Grantha character before the first such Tamil digit. However in texts that describe such usages, one can potentially just write the numerical forms. Hence it would be good if this can be fixed somehow...

**Comment by khaledhosny** [comment]
> The problem is that Harfbuzz guesses the script based on the first character of the buffer,

HarfBuzz script guessing is not usually used (and is not recommend to be used) because of issues like this. Applications typically implment a more sophisticated script itemization algorithm, and a base + combining mark almost always take the script if the combining mark (and if the base is a Common character, it will take the script of its surroundings).

In short, the behavior of HarfBuzz script guessing should be relied on since it is not what “serious” HarfBuzz clients use to set the script of the text.

**Comment by simoncozens** [comment]
> Hence it would be good if this can be fixed somehow...

I fixed it, I believe.
